src/django_project/core/urls/urls.py
from core import views
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import logout_then_login
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

urlpatterns = [
    # Django provided URLs
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("logout/", logout_then_login, name="logout"),
    # 3rd party URLs
    path("userextensions/", include("userextensions.urls")),
    path("handyhelpers/", include("handyhelpers.urls")),
    path("hostutils/", include("djangoaddicts.hostutils.urls")),
    path("pygwalker/", include("djangoaddicts.pygwalker.urls")),
    # RESTful API URLs
    path("rest/", include("core.urls.rest", namespace="rest")),
    path("rest/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("rest/swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger"),
    path("rest/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    # URLs to local apps
    path("", views.Index.as_view(), name="index"),
    path("dashboard/", views.ProjectDashboard.as_view(), name="dashboard"),
    path("parademgr/", include("parademgr.urls", namespace="parademgr")),
]

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

src/django_project/parademgr/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models
from django.utils import timezone
from handyhelpers.models import HandyHelperBaseModel
from parademgr.fields import UsPhoneNumberField


class Organization(HandyHelperBaseModel):
    """ """

    name = models.CharField(max_length=64, unique=True)
    description = models.CharField(max_length=255, blank=True)
    phone_numbers = models.ManyToManyField("PhoneNumber", blank=True)
    addresses = models.ManyToManyField("Address", blank=True)
    links = models.ManyToManyField("Link", blank=True)
    emails = models.ManyToManyField("EmailAddress", blank=True)
    contacts = models.ManyToManyField("Contact", blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = "Organizations"


class Contact(HandyHelperBaseModel):
    """ """

    first_name = models.CharField(max_length=64)
    last_name = models.CharField(max_length=64)
    phone_numbers = models.ManyToManyField("PhoneNumber", blank=True)
    addresses = models.ManyToManyField("Address", blank=True)
    links = models.ManyToManyField("Link", blank=True)
    emails = models.ManyToManyField("EmailAddress", blank=True)


class Address(HandyHelperBaseModel):
    address_type_choices = [
        ("Corporate", "Corporate"),
        ("Branch", "Branch"),
        ("Home", "Home"),
        ("Other", "Other"),
    ]

    street_address = models.CharField(max_length=255)
    address_extra = models.CharField(max_length=255, blank=True)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    postal_code = models.CharField(max_length=20)
    address_type = models.CharField(max_length=16, blank=True, choices=address_type_choices)

    def __str__(self):
        return f"{self.street_address}, {self.city}, {self.state} {self.postal_code}"


class PhoneNumber(HandyHelperBaseModel):

    phone_type_choices = [
        ("Direct", "Direct"),
        ("Fax", "Fax"),
        ("Home", "Home"),
        ("Mobile", "Mobile"),
        ("Office", "Office"),
        ("Other", "Other"),
    ]

    number = UsPhoneNumberField(null=False, blank=False, unique=True)
    phone_type = models.CharField(max_length=16, blank=True, choices=phone_type_choices)

    def __str__(self):
        return str(self.number)


class EmailAddress(HandyHelperBaseModel):
    email_address_type_choices = [
        ("Direct", "Direct"),
        ("Work", "Work"),
        ("Personal", "Personal"),
        ("Other", "Other"),
    ]
    email = models.EmailField(unique=True)
    email_address_type = models.CharField(max_length=16, blank=True, choices=email_address_type_choices)

    def __str__(self):
        return str(self.email)


class Link(HandyHelperBaseModel):
    name = models.CharField(max_length=32, blank=True)
    description = models.CharField(max_length=255, blank=True)
    url = models.URLField()

    def __str__(self):
        return self.url


class Parade(HandyHelperBaseModel):
    """ """

    current_year = timezone.datetime.now().year
    title = models.CharField(max_length=64, blank=True)
    year = models.IntegerField(
        validators=[MinValueValidator(2000), MaxValueValidator(current_year + 5)], help_text="Enter a valid year"
    )

    def __str__(self):
        return f"{self.year} {self.title}"

    # class Meta:
    #     verbose_name_plural = "Parades"

    def get_awards(self):
        """ """
        return ParticipantAward.objects.filter(parade=self).select_related(
            "award", "award__division", "award__division__category", "award__award_type", "parade", "winner"
        )

    def get_participants(self):
        """ """
        return Participant.objects.filter(parade=self).select_related(
            "division", "division__category", "organization", "parade"
        )


class Category(HandyHelperBaseModel):
    """ """

    name = models.CharField(max_length=32, unique=True)
    label = models.CharField(max_length=2, unique=True)
    description = models.CharField(max_length=255, blank=True)
    enabled = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        ordering = ["name", "label"]
        verbose_name_plural = "Categories"


class Division(HandyHelperBaseModel):
    """ """

    category = models.ForeignKey("Category", on_delete=models.CASCADE)
    label = models.CharField(max_length=2)
    name = models.CharField(max_length=64)
    description = models.CharField(max_length=255, blank=True)
    enabled = models.BooleanField(default=True)

    def __str__(self):
        return self.name

    class Meta:
        unique_together = (("category", "name"),)
        ordering = ["category", "label"]


class Participant(HandyHelperBaseModel):
    """ """

    parade = models.ForeignKey("Parade", on_delete=models.CASCADE)
    organization = models.ForeignKey("Organization", on_delete=models.CASCADE)
    division = models.ForeignKey("Division", on_delete=models.CASCADE)
    entry = models.IntegerField(blank=True, null=True)
    street = models.CharField(max_length=32, null=True)
    march_order = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.organization.name


class AwardType(HandyHelperBaseModel):
    """ """

    name = models.CharField(max_length=32, unique=True)
    description = models.CharField(max_length=255, blank=True)
    enabled = models.BooleanField(default=True)

    def __str__(self):
        return self.name


class Award(HandyHelperBaseModel):
    """ """

    award_type = models.ForeignKey("AwardType", on_delete=models.CASCADE)
    division = models.ForeignKey("Division", blank=True, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=32, blank=True)
    description = models.CharField(max_length=255, blank=True)
    amount = models.DecimalField(max_digits=10, decimal_places=2, blank=True, null=True)

    def __str__(self):
        return f"{self.division} - {self.name}" if self.division else self.name

    class Meta:
        unique_together = (("division", "name"),)


class ParticipantAward(HandyHelperBaseModel):
    award = models.ForeignKey("Award", on_delete=models.CASCADE)
    parade = models.ForeignKey("Parade", on_delete=models.CASCADE)
    winner = models.ForeignKey("Participant", blank=True, null=True, on_delete=models.CASCADE)


# register models with auditlog
# auditlog.register(MyModel)

src/django_project/parademgr/forms.py
# import models
# from parademgr.models import ()

src/django_project/parademgr/forms/create.py
from handyhelpers.forms import HtmxModelForm

# import models
from parademgr.models import Award, AwardType, Category, Division, Organization, Parade


class AwardForm(HtmxModelForm):
    hx_post = "/award"
    hx_target = "award-form"
    submit_button_text = "create"

    class Meta:
        model = Award
        fields = ["award_type", "division", "name", "description", "amount"]


class AwardTypeForm(HtmxModelForm):
    hx_post = "/awardtype"
    hx_target = "awardtype-form"
    submit_button_text = "create"

    class Meta:
        model = AwardType
        fields = ["name", "description"]


class CategoryForm(HtmxModelForm):
    hx_post = "/category"
    hx_target = "category-form"
    submit_button_text = "create"

    class Meta:
        model = Category
        fields = ["name", "label", "description"]


class DivisionForm(HtmxModelForm):
    hx_post = "/division"
    hx_target = "division-form"
    submit_button_text = "create"

    class Meta:
        model = Division
        fields = ["category", "name", "label", "description"]


class OrganizationForm(HtmxModelForm):
    hx_post = "/organization"
    hx_target = "organization-form"
    submit_button_text = "create"

    class Meta:
        model = Organization
        fields = ["name", "description"]

        labels = {
            "name": "Name",
            "description": "Description",
        }


class ParadeForm(HtmxModelForm):
    hx_post = "/parade"
    hx_target = "parade-form"
    submit_button_text = "create"

    class Meta:
        model = Parade
        fields = ["year", "title"]

        labels = {
            "year": "Year",
            "title": "Title",
        }

src/django_project/parademgr/views/gui.py
from django.views.generic import TemplateView
from handyhelpers.views.htmx import (
    CreateModelModalView,
    HtmxFilterModalView,
    HtmxItemizedView,
    HtmxOptionDetailView,
    HtmxOptionMultiFilterView,
)

# import forms
from parademgr.forms.create import (
    AwardForm,
    AwardTypeForm,
    CategoryForm,
    DivisionForm,
    OrganizationForm,
    ParadeForm,
)
from parademgr.forms.filter_forms import (
    AwardFilterForm,
    DivisionFilterForm,
    OrganizationFilterForm,
)

# import models
from parademgr.models import Award, AwardType, Category, Division, Organization, Parade


class Admin(HtmxItemizedView):
    """render the project index page"""

    template_name = "parademgr/full/custom/admin.html"
    htmx_template_name = "parademgr/partial/component/admin.htm"

    title = """<span class="text-primary">Parade Planner</span> <span class="text-secondary">Admin</span>"""
    subtitle = "Select an option below"
    item_list = [
        {
            "url": "/parademgr/create_award/",
            "icon": "fa-solid fa-award",
            "title": "Add Award",
            "description": "Add a new award",
        },
        {
            "url": "/parademgr/create_awardtype/",
            "icon": "fa-solid fa-certificate",
            "title": "Add Award Type",
            "description": "Add a new reward type",
        },
        {
            "url": "/parademgr/create_category/",
            "icon": "fas fa-table-list",
            "title": "Add Category",
            "description": "Add a new parade category",
        },
        {
            "url": "/parademgr/create_division",
            "icon": "fa-solid fa-users-rectangle",
            "title": "Add Division",
            "description": "Add a new parade division",
        },
        {
            "url": "/parademgr/create_parade/",
            "icon": "fa-regular fa-map",
            "title": "Create Parade",
            "description": "Create a new parade",
        },
    ]


class Test(TemplateView):
    template_name = "parademgr/full/custom/test.html"


class DetailParade(HtmxOptionDetailView):
    model = Parade
    initialize_tables = True
    htmx_template_name = "parademgr/partial/detail/parade.htm"
    template_name = "parademgr/full/detail/parade.html"


class DetailOrganization(HtmxOptionDetailView):
    model = Organization
    htmx_template_name = "parademgr/partial/detail/organization.htm"
    template_name = "parademgr/full/detail/organization.html"


class ListAwards(HtmxOptionMultiFilterView):
    """list available Award entries"""

    filter_form = AwardFilterForm
    model = Award
    queryset = Award.objects.all().select_related("division", "division__category")
    htmx_card_template_name = "parademgr/partial/card/awards.htm"
    htmx_table_template_name = "parademgr/partial/table/awards.htm"


class ListAwardTypes(HtmxOptionMultiFilterView):
    """list available AwardType entries"""

    model = AwardType
    queryset = AwardType.objects.all()
    htmx_table_template_name = "parademgr/partial/table/award_types.htm"


class ListCategories(HtmxOptionMultiFilterView):
    """list available Category entries"""

    model = Category
    htmx_table_template_name = "parademgr/partial/table/categories.htm"


class ListDivisions(HtmxOptionMultiFilterView):
    """list available Division entries"""

    filter_form = DivisionFilterForm
    model = Division
    queryset = Division.objects.all().select_related("category")
    htmx_table_template_name = "parademgr/partial/table/divisions.htm"


class ListOrganizations(HtmxOptionMultiFilterView):
    """list available Organization entries"""

    filter_form = OrganizationFilterForm
    model = Organization
    # htmx_list_template_name = "parademgr/partial/list/organizations.htm"
    htmx_table_template_name = "parademgr/partial/table/organizations.htm"


class ListParades(HtmxOptionMultiFilterView):
    """list available Parade entries"""

    model = Parade
    htmx_table_template_name = "parademgr/partial/table/parades.htm"


class CreateAwardModalView(CreateModelModalView):
    """Create a new Award entry"""

    form = AwardForm


class CreateAwardTypeModalView(CreateModelModalView):
    """Create a new AwardType entry"""

    form = AwardTypeForm


class CreateCategoryModalView(CreateModelModalView):
    """Create a new Category entry"""

    form = CategoryForm


class CreateDivisionModalView(CreateModelModalView):
    """Create a new Division entry"""

    form = DivisionForm


class CreateOrganization(CreateModelModalView):
    """Create a new Organization entry"""

    form = OrganizationForm


class CreateParadeModalView(CreateModelModalView):
    """Create a new Parade entry"""

    form = ParadeForm


class FilterAwardModalView(HtmxFilterModalView):
    """Create a new Award entry"""

    form = AwardFilterForm


class FilterDivisionModalView(HtmxFilterModalView):
    """Create a new Division entry"""

    form = DivisionFilterForm


class FilterOrganizationModalView(HtmxFilterModalView):
    """Create a new Organization entry"""

    form = OrganizationFilterForm

src/django_project/parademgr/views/report.py
""" report like pages for app models and data """

# from django.conf import settings
from django.shortcuts import render
from django.views.generic import View
from handyhelpers.views.report import (
    AnnualProgressView,
    AnnualStatView,
    AnnualTrendView,
)

# import models

# from handyhelpers.views.report import get_colors


class ParademgrDashboard(View):
    """parademgr dashboard"""

    template_name = "parademgr/custom/dashboard.html"

    def get(self, request):
        """render dashboard for parademgr specific data"""
        context = {"title": "Parademgr Dashboard"}
        return render(request, self.template_name, context=context)


class ParademgrAnnualProgressView(AnnualProgressView):
    """ """

    dataset_list: list = [
        # dict(
        #     title="Model",
        #     queryset=Model.objects.all(),
        #     dt_field="created_at",
        #     icon=Model.get_icon(),
        #     list_view="/storemgr/list_models",
        # ),
    ]


class ParademgrAnnualStatView(AnnualStatView):
    """ """

    dataset_list: list = [
        # dict(
        #     title="Model",
        #     queryset=Model.objects.all(),
        #     dt_field="created_at",
        #     icon=Model.get_icon(),
        #     list_view="/storemgr/list_models",
        # ),
    ]


class ParademgrAnnualTrendView(AnnualTrendView):
    """ """

    dataset_list: list = [
        # dict(
        #     title="Model",
        #     queryset=Model.objects.all(),
        #     dt_field="created_at",
        #     icon=Model.get_icon(),
        #     list_view="/storemgr/list_models",
        # ),
    ]

src/django_project/parademgr/templates/parademgr/partial/detail/organization.htm
<section class="animated fadeIn" style="animation-delay: .15s;">
    <header class="mt-2 mb-5">
        <div class="headline text-center">
            <div class="container">
                <div class="h1 text-primary fw-bold mb-3">{{ object }}</div>
                <div class="h3 text-secondary fw-bold mb-3">{{ object.description }}</div>
            </div>
        </div>
    </header>
</section>
<!-- 
<section>
    <div class="animated fadeIn" style="animation-delay: .25s;">
        <div class="container-fluid px-5">
            <div class="row text-center">
                <div class="col-12 col-md-4 mb-5">
                    <div class="card shadow" style="height: 60.5vh;">
                        <div class="card-title my-3 text-primary fw-bold h3">Details</div>
                        <div class="card-body" style="overflow-y: auto; overflow-x: hidden;">
                            <div class="row text-center">
                                <div class="col-12 my-3">
                                    <span class="text-primary h5 fw-bold">Phone Numbers:</span><br/>
                                    <span class="text-secondary">
                                        {% for phone_number in object.phone_numbers.all %}
                                        {{ phone_number.number }} <span class="small">({{ phone_number.get_phone_type_display }})</span><br/>
                                        {% endfor %}
                                    </span>
                                </div>
                                <div class="col-12 my-3"><span class="text-primary h5 fw-bold">Item Count:</span><br/><span class="text-secondary">{{ object.get_items.count }}</span></div>
                                {% if object.purchase_order %}
                                <div class="col-12 my-3"><span class="text-primary h5 fw-bold">Purchase Order:</span><br/><span class="text-secondary">{{ object.purchase_order }}</span></div>
                                {% endif %}
                                <div class="col-12 my-3"><span class="text-primary h5 fw-bold">Added By:</span><br/><span class="text-secondary">{{ object.added_by }}<br/><small>{{ object.created_at }}</small></span></div>
                                {% if object.purchased_by %}
                                <div class="col-12 my-3"><span class="text-primary h5 fw-bold">Purchased By:</span><br/><span class="text-secondary">{{ object.purchased_by }}<br/><small>{{ object.purchased_at }}</small></span></div>
                                {% endif %}
                                <div class="col-12 my-3"><span class="text-primary h5 fw-bold">Cost:</span><br/><span class="text-secondary">${{ object.get_cost|floatformat:2  }}</div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-12 col-md-8 mb-5"> 
                    <div class="row">
                        <div class="card shadow" style="height: 29vh;">
                            <div class="card-title my-3 text-primary fw-bold h3">Contacts</div>
                            <div class="card-body" style="overflow-y: auto; overflow-x: hidden;">
                                <ul class="list-group mx-auto justify-content-center" style="max-width: 91%; margin-top: .5%; margin-bottom: .5%">
                                    {% for item in object.contacts.all %}
                                    <div class="card shadow-sm hvr-grow my-2 py-1">
                                        <div class="row small mx-2">
                                            <div class="col-6 text-start">{{ item.first_name }} {{ item.last_name }}</div>
                                            <div class="col-6 text-start"></div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="card shadow" style="height: 29vh;">
                            <div class="card-title my-3 text-primary fw-bold h3">Parade Entries</div>
                            <div class="card-body" style="overflow-y: auto; overflow-x: hidden;">
                                <ul class="list-group mx-auto justify-content-center" style="max-width: 91%; margin-top: .5%; margin-bottom: .5%">
                                    {% for item in object.participant_set.all %}
                                    <div class="card shadow-sm hvr-grow my-2 py-1">
                                        <div class="row small mx-2">
                                            <div class="col-12 text-start">{{ item.parade }}: <span class="ms-2 text-secondary">{{ item.division }}</span></div>
                                        </div>
                                    </div>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section> -->

<div class="container my-5">
    <div class="row">
      <div class="col-12">
        <div class="grid-container">
          <div class="grid-item card">
            <div class="card-title">Details</div>
            <div class="card-body">
                <div class="row text-center">
                    <div class="col-12 my-3">
                        <span class="text-primary h6 fw-bold">Addresses:</span><br/>
                        <span class="text-secondary">
                            {% for item in object.addresses.all %}
                            <span class="small">{{ item }}</span><br/>
                            {% endfor %}
                        </span>
                    </div>
                </div>
                <div class="row text-center">
                    <div class="col-12 my-3">
                        <span class="text-primary h6 fw-bold">Phone Numbers:</span><br/>
                        <span class="text-secondary">
                            {% for phone_number in object.phone_numbers.all %}
                            {{ phone_number.number }} <span class="small">({{ phone_number.get_phone_type_display }})</span><br/>
                            {% endfor %}
                        </span>
                    </div>
                </div>
                <div class="row text-center">
                    <div class="col-12 my-3">
                        <span class="text-primary h6 fw-bold">Emails:</span><br/>
                        <span class="text-secondary">
                            {% for item in object.emails.all %}
                            <span class="small">{{ item }}</span><br/>
                            {% endfor %}
                        </span>
                    </div>
                </div>
                <div class="row text-center">
                    <div class="col-12 my-3">
                        <span class="text-primary h6 fw-bold">Links:</span><br/>
                        <span class="text-secondary">
                            {% for item in object.links.all %}
                            <span class="small">{{ item }}</span><br/>
                            {% endfor %}
                        </span>
                    </div>
                </div>
            </div>
          </div>

          <div class="grid-item card">
            <div class="card-title">
              Contacts
            </div>
            <div class="card-body">
                {% for item in object.contacts.all %}
                <div class="bordered-item hvr-grow">{{ item.first_name }} {{ item.last_name }}</div>
                {% endfor %}
            </div>
          </div>
          
          <div class="grid-item card">
            <div class="card-title">
              Parades
            </div>
            <div class="card-body">
                {% for item in object.participant_set.all %}
                <div class="bordered-item hvr-grow">{{ item.parade }}:<br/><span class="ms-2 text-secondary">{{ item.division }}</span></div>
                {% endfor %}
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  
  <!-- Custom CSS for Grid Layout -->
  <style>
    .grid-container {
      display: grid;
      grid-template-columns: 1fr 1fr;
      grid-template-rows: 1fr 1fr;
      gap: .5rem 1.75rem; /* Equal vertical and horizontal gap */
      height: 68vh; /* Take up available vertical space */
    }
  
    .grid-container > .card:first-child {
      grid-row: 1 / 3; /* First column spans both rows */
    }

  /* Ensure bordered items take full width */
  .bordered-item {
    width: 92%; /* Take full width of the card body */
    text-align: center; /* Optional: center text inside the item */
    background-color: var(--bs-light);
    font-size: .8rem;
    border: 1px solid #dee2e6; /* Bootstrap's default border style */
    padding: 0.5rem; /* Equivalent to Bootstrap's p-2 padding */
    margin-bottom: 0.5rem; /* To provide space between items */
    box-shadow: 0 0.125rem 0.25rem rgba(0, 0, 0, 0.075) !important;
  }

    .card-title {
        display: flex;
        justify-content: center; /* Centers horizontally */
        color: var(--bs-primary);
        font-weight: bold;
        font-size: 1.5rem;
        margin: 1rem;
    }

    /* Ensure the card body content takes full width */
    .card-body {
        /* display: flex; */
        justify-content: center; /* Centers horizontally */
        width: 100%; /* Ensure full width */
        height: 100%; /* Ensure full height of card */
        text-align: center; /* Optional: center text inside the card body */
    }
  
  
    /* Responsive behavior for small screens */
    @media (max-width: 768px) {
      .grid-container {
        grid-template-columns: 1fr; /* Single column on small screens */
        grid-template-rows: auto;   /* Each card takes its own row */
        gap: 1rem; /* Equal gap between rows in single column layout */
        height: auto; /* Remove fixed height for smaller screens */
      }
  
      .grid-container > .card:first-child {
        grid-row: auto; /* No need to span rows in a single column layout */
      }
    }
  </style>
  

src/django_project/parademgr/templates/parademgr/partial/detail/parade.htm
<section class="animated fadeIn" style="animation-delay: .15s;">
    <header class="m-2">
        <div class="headline text-center">
            <div class="container">
                <div class="h1 text-primary fw-bold mb-3">{{ object.year }}</div>
                <div class="h3 text-secondary fw-bold mb-3">{{ object.title }}</div>
            </div>
        </div>
    </header>

    <div class="container-fluid my-3 animated fadeIn" style="animation-delay: .25s;">
        <ul class="nav nav-tabs" id="myTab" role="tablist">
            <li class="nav-item" role="presentation">
              <button class="nav-link active" id="home-tab" data-bs-toggle="tab" data-bs-target="#participants" type="button" role="tab" aria-controls="participants" aria-selected="true">Participants</button>
            </li>
            <li class="nav-item" role="presentation">
              <button class="nav-link" id="awards-tab" data-bs-toggle="tab" data-bs-target="#awards" type="button" role="tab" aria-controls="awards" aria-selected="false">Awards</button>
            </li>
          </ul>
          <div class="tab-content" id="myTabContent">
            <div class="tab-pane fade show active" id="participants" role="tabpanel" aria-labelledby="participants-tab">
                {% with object.get_participants as queryset %}
                {% with 'parademgr/partial/table/participants.htm' as item_content %}
                {% include 'handyhelpers/htmx/bs5/htmx_option_multi_filter_view/wrapper_table.htm' %}
                {% endwith %}
                {% endwith %}
            </div>
            <div class="tab-pane fade" id="awards" role="tabpanel" aria-labelledby="awards-tab">
              {% with object.get_awards as queryset %}
              {% with 'parademgr/partial/table/participant_awards.htm' as item_content %}
              {% include 'handyhelpers/htmx/bs5/htmx_option_multi_filter_view/wrapper_table.htm' %}
              {% endwith %}
              {% endwith %}
            </div>
          </div>
    </div>
</section>