src/django_project/core/urls/urls.py
from core import views
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.views import logout_then_login
from django.urls import include, path
from drf_spectacular.views import (
    SpectacularAPIView,
    SpectacularRedocView,
    SpectacularSwaggerView,
)

urlpatterns = [
    # Django provided URLs
    path("admin/", admin.site.urls),
    path("accounts/", include("django.contrib.auth.urls")),
    path("logout/", logout_then_login, name="logout"),
    # 3rd party URLs
    path("userextensions/", include("userextensions.urls")),
    path("handyhelpers/", include("handyhelpers.urls")),
    path("hostutils/", include("djangoaddicts.hostutils.urls")),
    path("pygwalker/", include("djangoaddicts.pygwalker.urls")),
    # RESTful API URLs
    path("rest/", include("core.urls.rest", namespace="rest")),
    path("rest/schema/", SpectacularAPIView.as_view(), name="schema"),
    path("rest/swagger/", SpectacularSwaggerView.as_view(url_name="schema"), name="swagger"),
    path("rest/redoc/", SpectacularRedocView.as_view(url_name="schema"), name="redoc"),
    # URLs to local apps
    path("", views.Index.as_view(), name="index"),
    path("dashboard/", views.ProjectDashboard.as_view(), name="dashboard"),
    path("parademgr/", include("parademgr.urls", namespace="parademgr")),
]

if settings.DEBUG:
    urlpatterns.append(
        path("__debug__/", include("debug_toolbar.urls")),
    )

src/django_project/parademgr/forms.py
# import models
# from parademgr.models import ()

src/django_project/parademgr/forms/create.py
from handyhelpers.forms import HtmxModelForm

# import models
from parademgr.models import Award, AwardType, Category, Division, Organization, Parade


class AwardForm(HtmxModelForm):
    hx_post = "/award"
    hx_target = "award-form"
    submit_button_text = "create"

    class Meta:
        model = Award
        fields = ["award_type", "division", "name", "description", "amount"]


class AwardTypeForm(HtmxModelForm):
    hx_post = "/awardtype"
    hx_target = "awardtype-form"
    submit_button_text = "create"

    class Meta:
        model = AwardType
        fields = ["name", "description"]


class CategoryForm(HtmxModelForm):
    hx_post = "/category"
    hx_target = "category-form"
    submit_button_text = "create"

    class Meta:
        model = Category
        fields = ["name", "label", "description"]


class DivisionForm(HtmxModelForm):
    hx_post = "/division"
    hx_target = "division-form"
    submit_button_text = "create"

    class Meta:
        model = Division
        fields = ["category", "name", "label", "description"]


class OrganizationForm(HtmxModelForm):
    hx_post = "/organization"
    hx_target = "organization-form"
    submit_button_text = "create"

    class Meta:
        model = Organization
        fields = ["name", "description"]

        labels = {
            "name": "Name",
            "description": "Description",
        }


class ParadeForm(HtmxModelForm):
    hx_post = "/parade"
    hx_target = "parade-form"
    submit_button_text = "create"

    class Meta:
        model = Parade
        fields = ["year", "title"]

        labels = {
            "year": "Year",
            "title": "Title",
        }

src/django_project/parademgr/forms/filter_forms.py
from django import forms
from handyhelpers.forms import HtmxForm

# import models
from parademgr.models import AwardType, Category, Division

base_choices = [(None, "--------")]


class AwardFilterForm(HtmxForm):
    """ """

    modal_url = "/parademgr/awards/filter/"
    hx_post_url = "/parademgr/awards/"

    def __init__(self, *args, **kwargs):
        super(AwardFilterForm, self).__init__(*args, **kwargs)

    name__icontains = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"}), required=False, label="Name"
    )
    award_type = forms.ModelChoiceField(
        queryset=AwardType.objects.all(),
        widget=forms.Select(attrs={"class": "form-control"}),
        required=False,
        label="Award Type",
    )
    division = forms.ModelChoiceField(
        queryset=Division.objects.all(),
        widget=forms.Select(attrs={"class": "form-control"}),
        required=False,
        label="Division",
    )


class DivisionFilterForm(HtmxForm):
    modal_url = "/parademgr/divisions/filter/"
    hx_post_url = "/parademgr/divisions/"

    def __init__(self, *args, **kwargs):
        super(DivisionFilterForm, self).__init__(*args, **kwargs)

    name__icontains = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"}), required=False, label="Name"
    )
    category = forms.ModelChoiceField(
        queryset=Category.objects.all(),
        widget=forms.Select(attrs={"class": "form-control"}),
        required=False,
        label="Category",
    )


class OrganizationFilterForm(HtmxForm):
    modal_url = "/parademgr/organizations/filter/"
    hx_post_url = "/parademgr/organizations/"

    def __init__(self, *args, **kwargs):
        super(OrganizationFilterForm, self).__init__(*args, **kwargs)

    name__icontains = forms.CharField(
        widget=forms.TextInput(attrs={"class": "form-control"}), required=False, label="Name"
    )

src/django_project/core/views.py
from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, View
from handyhelpers.views import HandyHelperIndexView


class RegisterUser(CreateView):
    """add a new user"""

    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/register_user.html"


class Index(HandyHelperIndexView):
    """render the project index page"""

    title = """Welcome to <span class="text-primary">Parade Planner</span><span class="text-secondary"></span>!"""
    subtitle = "Select an option below to get started"
    item_list = [
        {
            "url": "/dashboard",
            "icon": """<i class="fa-solid fa-gauge-high"></i>""",
            "title": "Dashboard",
            "description": "View Parade Planner dashboard",
        },
        {
            "url": "/parademgr/admin",
            "icon": """<i class="fa-solid fa-id-card-clip"></i>""",
            "title": "Admin",
            "description": "Parade Planner administor page",
        },
        {
            "url": "/rest",
            "icon": """<i class="fa-solid fa-arrow-right-arrow-left"></i>""",
            "title": "APIs",
            "description": "List available RESTful APIs",
        },
    ]
    protected_item_list = [
        {
            "url": "/admin",
            "icon": """<i class="fa-brands fa-python"></i>""",
            "title": "Django Console",
            "description": "Access the django console",
        },
    ]
    protected_group_name = "admin"


class ProjectDashboard(View):
    """project-level dashboard"""

    template_name = "core/custom/dashboard.html"

    def get(self, request):
        """ """
        context = {}
        return render(request, self.template_name, context=context)

src/django_project/parademgr/views/gui.py
from django.views.generic import TemplateView
from handyhelpers.views.htmx import (
    CreateModelModalView,
    HtmxFilterModalView,
    HtmxItemizedView,
    HtmxOptionDetailView,
    HtmxOptionMultiFilterView,
)

# import forms
from parademgr.forms.create import (
    AwardForm,
    AwardTypeForm,
    CategoryForm,
    DivisionForm,
    OrganizationForm,
    ParadeForm,
)
from parademgr.forms.filter_forms import (
    AwardFilterForm,
    DivisionFilterForm,
    OrganizationFilterForm,
)

# import models
from parademgr.models import Award, AwardType, Category, Division, Organization, Parade


class Admin(HtmxItemizedView):
    """render the project index page"""

    template_name = "parademgr/full/custom/admin.html"
    htmx_template_name = "parademgr/partial/component/admin.htm"

    title = """<span class="text-primary">Parade Planner</span> <span class="text-secondary">Admin</span>"""
    subtitle = "Select an option below"
    item_list = [
        {
            "url": "/parademgr/create_award/",
            "icon": "fa-solid fa-award",
            "title": "Add Award",
            "description": "Add a new award",
        },
        {
            "url": "/parademgr/create_awardtype/",
            "icon": "fa-solid fa-certificate",
            "title": "Add Award Type",
            "description": "Add a new reward type",
        },
        {
            "url": "/parademgr/create_category/",
            "icon": "fas fa-table-list",
            "title": "Add Category",
            "description": "Add a new parade category",
        },
        {
            "url": "/parademgr/create_division",
            "icon": "fa-solid fa-users-rectangle",
            "title": "Add Division",
            "description": "Add a new parade division",
        },
        {
            "url": "/parademgr/create_parade/",
            "icon": "fa-regular fa-map",
            "title": "Create Parade",
            "description": "Create a new parade",
        },
    ]


class Test(TemplateView):
    template_name = "parademgr/full/custom/test.html"


class DetailParade(HtmxOptionDetailView):
    model = Parade
    initialize_tables = True
    htmx_template_name = "parademgr/partial/detail/parade.htm"
    template_name = "parademgr/full/detail/parade.html"


class DetailOrganization(HtmxOptionDetailView):
    model = Organization
    htmx_template_name = "parademgr/partial/detail/organization.htm"
    template_name = "parademgr/full/detail/organization.html"


class ListAwards(HtmxOptionMultiFilterView):
    """list available Award entries"""

    filter_form = AwardFilterForm
    model = Award
    queryset = Award.objects.all().select_related("division", "division__category")
    htmx_card_template_name = "parademgr/partial/card/awards.htm"
    htmx_table_template_name = "parademgr/partial/table/awards.htm"


class ListAwardTypes(HtmxOptionMultiFilterView):
    """list available AwardType entries"""

    model = AwardType
    queryset = AwardType.objects.all()
    htmx_table_template_name = "parademgr/partial/table/award_types.htm"


class ListCategories(HtmxOptionMultiFilterView):
    """list available Category entries"""

    model = Category
    htmx_table_template_name = "parademgr/partial/table/categories.htm"


class ListDivisions(HtmxOptionMultiFilterView):
    """list available Division entries"""

    filter_form = DivisionFilterForm
    model = Division
    queryset = Division.objects.all().select_related("category")
    htmx_table_template_name = "parademgr/partial/table/divisions.htm"


class ListOrganizations(HtmxOptionMultiFilterView):
    """list available Organization entries"""

    filter_form = OrganizationFilterForm
    model = Organization
    # htmx_list_template_name = "parademgr/partial/list/organizations.htm"
    htmx_table_template_name = "parademgr/partial/table/organizations.htm"


class ListParades(HtmxOptionMultiFilterView):
    """list available Parade entries"""

    model = Parade
    htmx_table_template_name = "parademgr/partial/table/parades.htm"


class CreateAwardModalView(CreateModelModalView):
    """Create a new Award entry"""

    form = AwardForm


class CreateAwardTypeModalView(CreateModelModalView):
    """Create a new AwardType entry"""

    form = AwardTypeForm


class CreateCategoryModalView(CreateModelModalView):
    """Create a new Category entry"""

    form = CategoryForm


class CreateDivisionModalView(CreateModelModalView):
    """Create a new Division entry"""

    form = DivisionForm


class CreateOrganization(CreateModelModalView):
    """Create a new Organization entry"""

    form = OrganizationForm


class CreateParadeModalView(CreateModelModalView):
    """Create a new Parade entry"""

    form = ParadeForm


class FilterAwardModalView(HtmxFilterModalView):
    """Create a new Award entry"""

    form = AwardFilterForm


class FilterDivisionModalView(HtmxFilterModalView):
    """Create a new Division entry"""

    form = DivisionFilterForm


class FilterOrganizationModalView(HtmxFilterModalView):
    """Create a new Organization entry"""

    form = OrganizationFilterForm

src/django_project/parademgr/views/report.py
""" report like pages for app models and data """

# from django.conf import settings
from django.shortcuts import render
from django.views.generic import View
from handyhelpers.views.report import (
    AnnualProgressView,
    AnnualStatView,
    AnnualTrendView,
)

# import models

# from handyhelpers.views.report import get_colors


class ParademgrDashboard(View):
    """parademgr dashboard"""

    template_name = "parademgr/custom/dashboard.html"

    def get(self, request):
        """render dashboard for parademgr specific data"""
        context = {"title": "Parademgr Dashboard"}
        return render(request, self.template_name, context=context)


class ParademgrAnnualProgressView(AnnualProgressView):
    """ """

    dataset_list: list = [
        # dict(
        #     title="Model",
        #     queryset=Model.objects.all(),
        #     dt_field="created_at",
        #     icon=Model.get_icon(),
        #     list_view="/storemgr/list_models",
        # ),
    ]


class ParademgrAnnualStatView(AnnualStatView):
    """ """

    dataset_list: list = [
        # dict(
        #     title="Model",
        #     queryset=Model.objects.all(),
        #     dt_field="created_at",
        #     icon=Model.get_icon(),
        #     list_view="/storemgr/list_models",
        # ),
    ]


class ParademgrAnnualTrendView(AnnualTrendView):
    """ """

    dataset_list: list = [
        # dict(
        #     title="Model",
        #     queryset=Model.objects.all(),
        #     dt_field="created_at",
        #     icon=Model.get_icon(),
        #     list_view="/storemgr/list_models",
        # ),
    ]

src/django_project/parademgr/templates/parademgr/full/custom/admin.html
{% extends BASE_TEMPLATE|default:"base.htm" %}
{% load static %}

{% block content %}
    {% if request.is_htmx %}
    <div 
    hx-get="{% url 'parademgr:admin' %}" 
    hx-trigger="load"
    ></div>
    {% else %}
    <div>{% include 'parademgr/partial/component/admin.htm' %}</div>
    {% endif %}

{% endblock content %}

src/django_project/parademgr/templates/parademgr/full/custom/test copy.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sortable Table</title>
    <!-- <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet"> -->
    <link href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">


    <style>
        th.sortable {
            cursor: pointer;
            position: relative;
        }
        th.sortable .fa {
            margin-left: 5px;
            color: gray;
        }
        th.sortable .fa.sort-active {
            color: black;
        }
        th.sortable .fa-sort {
            visibility: hidden;
        }
        th.sortable:hover .fa-sort {
            visibility: visible;
        }
    </style>
</head>
<body>
    <div class="container mt-4">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th class="sortable">Name <i class="fa fa-sort fa-sort-up"></i><i class="fa fa-sort fa-sort-down"></i></th>
                    <th class="sortable">Age <i class="fa fa-sort fa-sort-up"></i><i class="fa fa-sort fa-sort-down"></i></th>
                    <th class="sortable">City <i class="fa fa-sort fa-sort-up"></i><i class="fa fa-sort fa-sort-down"></i></th>
                </tr>
            </thead>
            <tbody>
                <tr><td><a href="#">John Doe</a></td><td>28</td><td>New York</td></tr>
                <tr><td><a href="www.google.com">Jane Smith</a></td><td>22</td><td>San Francisco</td></tr>
                <tr><td>Michael Brown</td><td>32</td><td>Chicago</td></tr>
                <tr><td><a href="#">Emily White</a></td><td>30</td><td>Los Angeles</td></tr>
                <tr><td>William Johnson</td><td>27</td><td>Houston</td></tr>
                <tr><td>Patricia Taylor</td><td>29</td><td>Phoenix</td></tr>
                <tr><td>Linda Anderson</td><td>33</td><td>Philadelphia</td></tr>
                <tr><td><a href="www.yahoo.com">David Harris A</a></td><td>31</td><td>San Antonio</td></tr>
                <tr><td><a href="www.google.com">David Harris B</a></td><td>31</td><td>San Antonio</td></tr>
                <tr><td>Barbara Martinez</td><td>26</td><td>Dallas</td></tr>
                <tr><td>Richard Clark</td><td>34</td><td>Austin</td></tr>
                <tr><td>Joseph Lewis</td><td>25</td><td>San Diego</td></tr>
                <tr><td>Thomas Robinson</td><td>28</td><td>Fort Worth</td></tr>
            </tbody>
        </table>
        <nav>
            <ul class="pagination justify-content-center">
                <!-- Pagination will be inserted here by JavaScript -->
            </ul>
        </nav>
    </div>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script> -->
    <script type="text/javascript" src="{% static 'node_modules/@popperjs/core/dist/umd/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'node_modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    
    <!-- <script src="sortable.js"></script> -->
    <script type="text/javascript" src="{% static 'paradeplanner/js/sortable.js' %}"></script>
</body>
</html>

src/django_project/parademgr/templates/parademgr/full/custom/test.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sortable Table</title>
    <!-- <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet"> -->
    <link href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css"> -->
    <link href="{% static 'node_modules/@fortawesome/fontawesome-free/css/all.min.css' %}" rel="stylesheet">


    <link href="{% static 'paradeplanner/css/sortable.css' %}" rel="stylesheet">

</head>
<body>
    <div class="container mt-4">
        <div class="d-flex justify-content-end mb-3">
            <i id="paginationToggle" class="fa-solid fa-square-caret-down"></i>
            <!-- <span class="ms-2">Enable Pagination</span> -->
        </div>
        <table class="table table-condensed table-bordered table-striped mt-3">
            <thead>
                <tr>
                    <th class="sortable">Name <i class="fa fa-sortable fa-sort-up"></i><i class="fa fa-sortable fa-sort-down"></i></th>
                    <th class="sortable">Age <i class="fa fa-sortable fa-sort-up"></i><i class="fa fa-sortable fa-sort-down"></i></th>
                    <th class="sortable">City <i class="fa fa-sortable fa-sort-up"></i><i class="fa fa-sortable fa-sort-down"></i></th>
                </tr>
            </thead>
            <tbody>
                    <tr><td><a href="#">John Doe</a></td><td>28</td><td>New York</td></tr>
                    <tr><td><a href="www.google.com">Jane Smith</a></td><td>22</td><td>San Francisco</td></tr>
                    <tr><td>Michael Brown</td><td>32</td><td>Chicago</td></tr>
                    <tr><td><a href="#">Emily White</a></td><td>30</td><td>Los Angeles</td></tr>
                    <tr><td>William Johnson</td><td>27</td><td>Houston</td></tr>
                    <tr><td>Patricia Taylor</td><td>29</td><td>Phoenix</td></tr>
                    <tr><td>Linda Anderson</td><td>33</td><td>Philadelphia</td></tr>
                    <tr><td><a href="www.yahoo.com">David Harris A</a></td><td>31</td><td>San Antonio</td></tr>
                    <tr><td><a href="www.google.com">David Harris B</a></td><td>31</td><td>San Antonio</td></tr>
                    <tr><td>Barbara Martinez</td><td>26</td><td>Dallas</td></tr>
                    <tr><td>Richard Clark</td><td>34</td><td>Austin</td></tr>
                    <tr><td>Joseph Lewis</td><td>25</td><td>San Diego</td></tr>
                    <tr><td>Thomas Robinson</td><td>28</td><td>Fort Worth</td></tr>
            </tbody>
        </table>
        <nav id="paginationNav">
            <ul class="pagination justify-content-end">
                <!-- Pagination will be inserted here by JavaScript -->
            </ul>
        </nav>
    </div>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script> -->
    <script type="text/javascript" src="{% static 'node_modules/@popperjs/core/dist/umd/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'node_modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    
    <!-- <script src="sortable.js"></script> -->
    <script type="text/javascript" src="{% static 'paradeplanner/js/sortable.js' %}"></script>
</body>
</html>

src/django_project/parademgr/templates/parademgr/full/custom/test1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Sortable Table</title>
    <!-- <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet"> -->
    <link href="{% static 'node_modules/bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <style>
.dataTables_length,
.dataTables_wrapper {
  font-size: 1.6rem;
}
.dataTables_length select,
.dataTables_length input,
.dataTables_wrapper select,
.dataTables_wrapper input {
  background-color: #f9f9f9;
  border: 1px solid #999;
  border-radius: 4px;
  height: 3rem;
  line-height: 2;
  font-size: 1.8rem;
  color: #333;
}
.dataTables_length .dataTables_length,
.dataTables_length .dataTables_filter,
.dataTables_wrapper .dataTables_length,
.dataTables_wrapper .dataTables_filter {
  margin-top: 30px;
  margin-right: 20px;
  margin-bottom: 10px;
  display: inline-flex;
}

.paginate_button {
  min-width: 4rem;
  display: inline-block;
  text-align: center;
  padding: 1rem 1.6rem;
  margin-top: -1rem;
  border: 2px solid lightblue;
}
.paginate_button:not(.previous) {
  border-left: none;
}
.paginate_button.previous {
  border-radius: 8px 0 0 8px;
  min-width: 7rem;
}
.paginate_button.next {
  border-radius: 0 8px 8px 0;
  min-width: 7rem;
}
.paginate_button:hover {
  cursor: pointer;
  background-color: #eee;
  text-decoration: none;
}
    </style>
</head>
<body>
    <div class="container mt-4">
        <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
            <thead>
              <tr>
                <th>Name</th>
                <th>Position</th>
                <th>Office</th>
                <th>Age</th>
                <th>Start date</th>
                <th>Salary</th>
              </tr>
            </thead>
            <tfoot>
              <tr>
                <th>Name</th>
                <th>Position</th>
                <th>Office</th>
                <th>Age</th>
                <th>Start date</th>
                <th>Salary</th>
              </tr>
            </tfoot>
            <tbody>
              <tr>
                <td>Tiger Nixon</td>
                <td>System Architect</td>
                <td>Edinburgh</td>
                <td>61</td>
                <td>2011/04/25</td>
                <td>$320,800</td>
              </tr>
              <tr>
                <td>Garrett Winters</td>
                <td>Accountant</td>
                <td>Tokyo</td>
                <td>63</td>
                <td>2011/07/25</td>
                <td>$170,750</td>
              </tr>
              <tr>
                <td>Ashton Cox</td>
                <td>Junior Technical Author</td>
                <td>San Francisco</td>
                <td>66</td>
                <td>2009/01/12</td>
                <td>$86,000</td>
              </tr>
              <tr>
                <td>Cedric Kelly</td>
                <td>Senior Javascript Developer</td>
                <td>Edinburgh</td>
                <td>22</td>
                <td>2012/03/29</td>
                <td>$433,060</td>
              </tr>
              <tr>
                <td>Airi Satou</td>
                <td>Accountant</td>
                <td>Tokyo</td>
                <td>33</td>
                <td>2008/11/28</td>
                <td>$162,700</td>
              </tr>
              <tr>
                <td>Brielle Williamson</td>
                <td>Integration Specialist</td>
                <td>New York</td>
                <td>61</td>
                <td>2012/12/02</td>
                <td>$372,000</td>
              </tr>
              <tr>
                <td>Herrod Chandler</td>
                <td>Sales Assistant</td>
                <td>San Francisco</td>
                <td>59</td>
                <td>2012/08/06</td>
                <td>$137,500</td>
              </tr>
              <tr>
                <td>Rhona Davidson</td>
                <td>Integration Specialist</td>
                <td>Tokyo</td>
                <td>55</td>
                <td>2010/10/14</td>
                <td>$327,900</td>
              </tr>
              <tr>
                <td>Colleen Hurst</td>
                <td>Javascript Developer</td>
                <td>San Francisco</td>
                <td>39</td>
                <td>2009/09/15</td>
                <td>$205,500</td>
              </tr>
              <tr>
                <td>Sonya Frost</td>
                <td>Software Engineer</td>
                <td>Edinburgh</td>
                <td>23</td>
                <td>2008/12/13</td>
                <td>$103,600</td>
              </tr>
              <tr>
                <td>Jena Gaines</td>
                <td>Office Manager</td>
                <td>London</td>
                <td>30</td>
                <td>2008/12/19</td>
                <td>$90,560</td>
              </tr>
              <tr>
                <td>Quinn Flynn</td>
                <td>Support Lead</td>
                <td>Edinburgh</td>
                <td>22</td>
                <td>2013/03/03</td>
                <td>$342,000</td>
              </tr>
              <tr>
                <td>Charde Marshall</td>
                <td>Regional Director</td>
                <td>San Francisco</td>
                <td>36</td>
                <td>2008/10/16</td>
                <td>$470,600</td>
              </tr>
              <tr>
                <td>Haley Kennedy</td>
                <td>Senior Marketing Designer</td>
                <td>London</td>
                <td>43</td>
                <td>2012/12/18</td>
                <td>$313,500</td>
              </tr>
              <tr>
                <td>Tatyana Fitzpatrick</td>
                <td>Regional Director</td>
                <td>London</td>
                <td>19</td>
                <td>2010/03/17</td>
                <td>$385,750</td>
              </tr>
              <tr>
                <td>Michael Silva</td>
                <td>Marketing Designer</td>
                <td>London</td>
                <td>66</td>
                <td>2012/11/27</td>
                <td>$198,500</td>
              </tr>
              <tr>
                <td>Paul Byrd</td>
                <td>Chief Financial Officer (CFO)</td>
                <td>New York</td>
                <td>64</td>
                <td>2010/06/09</td>
                <td>$725,000</td>
              </tr>
              <tr>
                <td>Gloria Little</td>
                <td>Systems Administrator</td>
                <td>New York</td>
                <td>59</td>
                <td>2009/04/10</td>
                <td>$237,500</td>
              </tr>
              <tr>
                <td>Bradley Greer</td>
                <td>Software Engineer</td>
                <td>London</td>
                <td>41</td>
                <td>2012/10/13</td>
                <td>$132,000</td>
              </tr>
              <tr>
                <td>Dai Rios</td>
                <td>Personnel Lead</td>
                <td>Edinburgh</td>
                <td>35</td>
                <td>2012/09/26</td>
                <td>$217,500</td>
              </tr>
              <tr>
                <td>Jenette Caldwell</td>
                <td>Development Lead</td>
                <td>New York</td>
                <td>30</td>
                <td>2011/09/03</td>
                <td>$345,000</td>
              </tr>
         
            </tbody>
          </table>
    </div>
    <!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.bundle.min.js"></script> -->
    <script type="text/javascript" src="{% static 'node_modules/@popperjs/core/dist/umd/popper.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'node_modules/bootstrap/dist/js/bootstrap.min.js' %}"></script>
    
    <!-- <script src="sortable.js"></script> -->
    <script>
        $(document).ready(function() {
        $("#example").DataTable();
        });
    </script>
</body>
</html>